import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "../globals.css";
import { Sidebar,Navbar } from "../../components/index";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} antialiased flexStart  w-full h-full`}
      >
        <Sidebar/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
